### ISSUE TITLE
A dot name structure assignment is illegal when the structure is empty.

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/SPM#13] opened 2018-04-28 15:35 UTC
https://openneuro.org/datasets/ds000224/versions/00001/logs/SPM%2Fdefault%2Fda15ae7a-9bc7-4a67-819f-9388aca41516

```
Execution failed: /opt/spm12/spm_BIDS_App.m
A dot name structure assignment is illegal when the structure is empty.  Use a subscript on the structure.
Error in spm_BIDS (line 97)
Error in spm (line 1210)
Error in spm_standalone (line 115)
```

**Comment by gllmflndn** [comment] 2018-05-22 14:16
I couldn't reproduce this. The one way I can think of that would generate such error would be if `participants.json` was present but not `participants.tsv`, which is not the case in this dataset. Could something have happened to the dataset during the execution of the job?

**Comment by gllmflndn** [comment] 2019-08-28 08:45
Closing this report as issue could not be reproduced. Please reopen if necessary.

**Closed as completed by gllmflndn** 2019-08-28 08:45 UTC
Labels: bug
